# Mandatory settings

name: Taejae Han
paginate: 25
paginate_path: "/posts/page/:num/"
url: https://blog.hantaejae.com/
blog_theme: light # Or use dark

# Optional settings

discus_identifier: # Add your Disqus identifier
ga_analytics: UA-90155456-1
rss_enabled: false # Change to false if not
about_enabled: true # Change to true if you wish to show an icon in the navigation that redirects to the about page
social:
  dribbble: # Add your Dribbble handle
  facebook: TaejaeHan
  flickr: # Add your Flickr handle
  github: taejaehan
  linkedin: #taejae-han-8b5b32ba
  twitter: #HANTAEJAE
  email: hantaejae@gmail.com
  bitcoin: # Add your Bitcoin link or address

# Important settings (change at own risk)

assets:
  compress:
    css: true
    js: true
  features:
    automatic_img_size: false
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
permalink: posts/:slug
